/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SecurityLoginOkResponse {
    message: string;
    data: {
        id: string;
        expiration_date: string;
        email: string;
        token: string;
        timestamp: string;
    };
}
