export const SAMPLE_EULA = `Eaton Brightlayer Industrial

Last Revised Date: October 30, 2020

Eaton Corporation (“EATON”) owns and operates the Eaton Brightlayer Industrial  application software (“Product Software”). The following Eaton Brightlayer Industrial End-User License Agreement (“Agreement”) governs the use of this Product Software. Other sites, content or online services owned or controlled by Eaton have their own terms of use/end-user license agreement and should be reviewed. Eaton licenses the use of the Product Software to you subject to the terms of this Agreement. The following Privacy Policy also applies to your use of the Product Software: https://www.eaton.com/content/eaton/us/en-us/company/policies-and-statements/privacy-cookies-and-data-protection.html 

IMPORTANT, PLEASE READ THIS AGREEMENT BEFORE REGISTERING, ACCESSING OR  USING THE PRODUCT SOFTWARE. THIS AGREEMENT IS A BINDING LEGAL CONTRACT BETWEEN YOU AND/OR THE ENTITY YOU REPRESENT (“AUTHORIZED PARTY”) AND EATON, TOGETHER WITH ITS AFFILIATES ENTITIES AND SUBSIDIARIES. BY CLICKING THE “I have read and agree to the Terms & Conditions” BUTTON BELOW, OR BY ACCESSING OR USING THE PRODUCT SOFTWARE, AUTHORIZED PARTY IS AGREEING TO BE BOUND BY THIS AGREEMENT. AUTHORIZED PARTY’S RIGHT TO USE THE PRODUCT SOFTWARE IS LIMITED BY APPLICABLE LAWS IN ITS JURISDICTION. 

IF AUTHORIZED PARTY DOES NOT ACCEPT THE TERMS IN THIS AGREEMENT, DO NOT CLICK THE “I HAVE READ AND UNDERSTAND THIS AGREEMENT” CHECKBOX AND THE “Next” BUTTON AND DO NOT REGISTER, ACCESS OR USE THE PRODUCT SOFTWARE IN ANY WAY.

Description of the Product Software.  Eaton Brightlayer Industrial is a set of software products designed to monitor, alarm and report on telemetry and event data from edge devices.  The software consists of a cloud-based component hosted in Microsoft Azure, a dashboarding application accessible via browsers and a native mobile application for iOS and Android.

License. Subject to the terms and conditions of this Agreement, Eaton hereby grants to Authorized Party a limited, non-transferable, non-sublicensable, non-assignable, non-exclusive and revocable license to access and use the Product Software in conjunction with the operation of Eaton products to which the Product Software pertains or other products as described by Eaton in any user guides and manuals for access to and use of the Product Software (“Documentation”) solely for Authorized Party’s own internal business purpose use and only in a manner that is consistent with the terms of this Agreement (“License”). In the event Eaton requires Authorized Party to register as an end-user, such license is valid only if the registration is complete and accurate. 

Restrictions. This Agreement does not allow Authorized Party to copy, decompile, reverse engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the Product Software, or any updates or upgrades, or any part thereof. Authorized Party may not use any part of the Product Software to establish any independent data files, databases, compendiums or any other reference materials. Any attempt to do so is a violation of the rights of Eaton. If Authorized Party breaches these restrictions, Authorized Party may be subject to prosecution and damages. The Product Software is intended for adults and by accessing the Product Software, Authorized Party represents that they are of or exceeding the minimum legal age threshold of an adult.

Prohibited Conduct. In connection with the Authorized Party’s access to and/or use of the Product Software, the Authorized Party agrees not to:

- Violate any laws or regulations.
- Upload/post anything that imposes an unreasonable or disproportionately large strain on Eaton’s network or computer infrastructure.
- Engage in any behavior that is designed to hack into or gain unauthorized access to protected areas of the Product Software and/or Eaton’s computers, servers or networks, and/or any computers or systems used by other users of the Product Software.
- Upload/post anything that could destroy, damage, or impair any portion of the Product Software or any computers, systems, hardware, or software used by Eaton or other users.
- Make unauthorized attempts to modify any information stored in the Product Software.
- Make attempts to defeat or circumvent security features, or to utilize the Product Software for any purpose other than its intended purposes.
- Upload/post any unsolicited or unauthorized advertising, promotional materials, spam emails, chain letters, pyramid schemes, or any other form of such solicitations.
- Use any automated technology such as a robot, spider, or scraper to access, scrape, or data mine the Product Software.
- Provide false or misleading information when signing up for a Product Software account or otherwise upload/post any false or misleading information or content through the Product Software.

The previous list of prohibitions is not exclusive or exhaustive. Eaton reserves the right to terminate the Authorized Party’s access to the Product Services for any violation of this Agreement.

Updates and Events outside of Eaton’s control. Eaton may update or upgrade the Product Software at any time. Certain functions of the Product Software may be modified or discontinued as a result of any such updates or upgrades. If Eaton elects to provide maintenance or support of any kind, Eaton may terminate that maintenance or support at any time without notice to Authorized Party. The terms and conditions of this Agreement shall govern any upgrades or updates provided by Eaton that replace and/or supplement the original Product Software, unless such upgrade is accompanied by, or references, a separate license agreement in which case the terms of that license agreement shall govern.

Eaton will not be liable or responsible for any failure to perform, or delay in performance of, any of Eaton’s obligations under this Agreement that is caused by any act or event beyond Eaton’s reasonable control, including but not limited to, acts of God, failure of public or private telecommunications networks, changes in law or regulation, or any other force majeure event or circumstance, whether or not foreseeable.
Proprietary Rights.  Eaton owns all rights, title and interest in, and to, without limitation, all intellectual and proprietary rights of any and all featured products or parts, including, but not limited to, any models, data, or formulas exhibited in the Product Software excluding any Open Source Software as defined below that may be contained herein, and, except for the limited license granted to Authorized Party herein, nothing in this Agreement shall be construed to restrict, transfer, convey, encumber, alter, impair or otherwise adversely affect Eaton’s ownership or proprietary rights therein or any other of Eaton’s information, processes, methodologies, products, goods, services, or materials, tangible or intangible, in any form and in any medium. Authorized Party may not copy, decompile, or reverse engineer any of the products featured in the Product Software.
Open Source. Certain items of software included with the Product Software may be subject to “open source” or “free software” licenses (“Open Source Software”). Some of the Open Source Software is owned by third parties. The Open Source Software is not subject to the terms and conditions of this EULA. Instead, each item of Open Source Software is licensed under the terms of the end user license that accompanies such Open Source Software. Nothing in this Agreement limits Authorized Party’s rights under, or grants Authorized Party rights that supersede, the terms and conditions of any applicable end user license for the Open Source Software. To the extent there are any conflicts between the terms of this Agreement and any Open Source Software license corresponding to the open source component(s) of the software included with the Product Software or additional obligations by such Open Source Software license that are not set forth in this Agreement, the terms of the Open Source Software license will control. Eaton provides the Open Source Software to Authorized Party “AS IS” without any indemnities or warranties of any kind.

Fees. Eaton charges Authorized Party a monthly service fee for access to the Product Software. Authorized Party agrees to pay all fees and charges, including applicable taxes, incurred through Authorized Party’s account at the rates in effect for the billing period in which such fees and charges are incurred, including but not limited to, charges for any products or services offered for sale through the Product Software by Eaton (such fees, charges and taxes shall collectively be referred to as “Fees”).  Eaton reserves the right to change the amount of, or basis for determining, any Fees, and to institute new Fees, effective upon prior notice to Authorized Party.

Support Services. Eaton or its suppliers and distributors may provide Authorized Party with support services related to the Product Software ("Support Services"). Use of Support Services is governed by the policies and programs described in the Documentation, and/or other Eaton-provided materials. Any supplemental materials provided to Authorized Party as part of the Support Services shall be considered part of the Product Software, as applicable, and subject to the terms and conditions of this Agreement.

No Warranty.  TO THE EXTENT PERMITTED BY LAW, AUTHORIZED PARTY EXPRESSLY ACKNOWLEDGES AND AGREES THAT USE OF THE PRODUCT SOFTWARE IS AT AUTHORIZED PARTY’S SOLE RISK AND THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND EFFORT OF THE PRODUCT SOFTWARE IS WITH AUTHORIZED PARTY. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE PRODUCT SOFTWARE AND ANY SERVICES PERFORMED OR PROVIDED BY OR IN CONNECTION WITH THE PRODUCT SOFTWARE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITH ALL BUGS AND FAULTS AND WITHOUT WARRANTY OF ANY KIND. EATON, ITS AFFILIATES, SUBSIDIARIES, AND AUTHORIZED REPRESENTATIVES HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS OF ANY KIND WITH RESPECT TO THE PRODUCT SOFTWARE AND ANY SERVICES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING, BUT WITHOUT LIMITATION, ANY IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, OF SATISFACTORY QUALITY, OF FITNESS FOR A PARTICULAR PURPOSE, SECURITY, COMPLETENESS, TIMELINESS, ACCURACY, QUIET ENJOYMENT, TITLE, FREEDOM FROM COMPUTER VIRUSES, AND OF NON-INFRINGEMENT OF THIRD PARTY RIGHTS. NEITHER EATON, NOR ANY OF ITS AFFILIATES OR SUBSIDIARIES, WARRANT THAT THE FUNCTIONS OR SERVICES CONTAINED IN, ACCESSED FROM, PERFORMED BY, DISPLAYED ON, LINKED TO/FROM, OR PROVIDED BY, THE PRODUCT SOFTWARE WILL MEET AUTHORIZED PARTY’S REQUIREMENTS, THAT THE OPERATION OF THE PRODUCT SOFTWARE OR SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, TIMELY, SECURE, OR THAT DEFECTS OR ERRORS IN THE PRODUCT SOFTWARE OR SERVICES WILL BE CORRECTED, OR THAT THE PRODUCT SOFTWARE WILL BE COMPATIBLE WITH ANY SYSTEM, OR THAT THE PRODUCT SOFTWARE WILL BE FREE FROM WORMS, VIRUSES, MALWARE, TROJAN HORSES, OR OTHER HARMFUL OR DISABLING COMPONENTS.  NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY EATON, ITS AFFILIATES, SUBSIDIARIES, OR ANY OF THEIR RESPECTIVE AUTHORIZED REPRESENTATIVES SHALL CREATE A WARRANTY.  AUTHORIZED PARTY ASSUMES THE ENTIRE COST OF ANY AND ALL NECESSARY REPAIRS IN THE EVENT AUTHORIZED PARTY EXPERIENCES ANY LOSS OR DAMAGE ARISING FROM THE USE OF THE PRODUCT SOFTWARE OR ANY RELATED GOODS OR SERVICES. IF AUTHORIZED PARTY IS DISSATISFIED WITH THIS AGREEMENT, THE PRODUCT SOFTWARE AND/OR ANY RELATED GOODS OR SERVICES, AUTHORIZED PARTY’S SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE PRODUCT SOFTWARE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO AUTHORIZED PARTY.

Limitation of Liability.  TO THE EXTENT PERMITTED BY LAW, IN NO EVENT WILL EATON OR ITS OFFICERS, DIRECTORS, EMPLOYEES, AFFILIATES, SUBSIDIARIES AGENTS, LICENSORS, AUTHORIZED REPRESENTATIVES, ATTORNEYS AND/OR BUSINESS PARTNERS, NOR ANY PARTY INVOLVED IN THE CREATION, PRODUCTION, OR TRANSMISSION OF THE PRODUCT SOFTWARE, BE LIABLE FOR ANY LOSS OR DAMAGE OF ANY KIND WHATSOEVER, INCLUDING, BUT NOT LIMITED TO, ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, STATUTORY, PUNITIVE, ACTUAL, LIQUIDATED, EXEMPLARY, CONSEQUENTIAL OR OTHER DAMAGES, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF REVENUE, LOSS OF DATA, LOSS OF PRODUCTION, LOSS OF GOODWILL,  INTELLECTUAL PROPERTY INFRINGEMENT, BUSINESS INTERRUPTION OR LOSS OF USE, PAIN AND SUFFERING, EMOTIONAL DISTRESS OR SIMILAR DAMAGES, OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO AUTHORIZED PARTY’S USE OR INABILITY TO USE THE PRODUCT SOFTWARE, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT OR OTHERWISE) AND EVEN IF EATON OR THE AFOREMENTIONED PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

TO THE EXTENT PERMITTED BY LAW, IN NO EVENT WILL THE COLLECTIVE LIABILITY OF EATON OR THE AFOREMENTIONED PARTIES, REGARDLESS OF THE TYPE OF ACTION, WHETHER IN CONTRACT, TORT, OR OTHERWISE, EXCEED THE GREATER OF $100.00 OR THE AMOUNT THE AUTHORIZED PARTY PAID TO EATON AND/OR THE AFOREMENTIONED PARTIES FOR THE APPLICABLE GOODS OR SERVICES OUT OF WHICH THE LIABILITY AROSE.

Indemnification.  Authorized Party agrees to indemnify, defend, and hold harmless Eaton, including its officers, directors, employees, affiliates, subsidiaries, agents, licensors, authorized representatives, attorneys, business partners, and respective successors and assigns (“Indemnified Parties”) from and against any and all claims, demands, actions, liabilities, judgments, awards, losses, damages, costs and expenses (including reasonable attorneys' fees, costs of defense, and direct, indirect, punitive, special, individual, consequential, or exemplary damages), Eaton or any of the Indemnified Parties suffer in relation to, arising from, or from the purpose of avoiding, any claim or demand from a third party that relates to Authorized Party’s: (a) breach or violation of this Agreement; (b) infringement, misappropriation or any violation of the rights of any other party from use of the Product Software in violation of this Agreement; (c) violation or non-compliance with any applicable law, rule, guidelines, acts, decrees, orders or regulations; (d) use, alteration or export of the Product Software (or any component thereof) in violation of this Agreement; and (e) the use of the Product Software by Authorized Party or any person using Authorized Party’s account. Eaton and its affiliates reserve the right to assume the exclusive defense and control of any claims or actions subject to indemnification by Authorized Party and all negotiations for its settlement or compromise, and Authorized Party agrees to fully cooperate with Eaton and its affiliates upon request by Eaton.
Amendments to this Agreement.  Eaton may modify, add or remove any of the terms and conditions of this Agreement at its sole discretion at any time without prior notice. Authorized Party will know when a change to this Agreement has been made, as there will be a change to the “Last Revised Date” noted at the start of this Agreement. Authorized Party should visit this registration site from time to time to review the current terms of the Agreement. Any changes will be effective from the Last Revised Date. Authorized Party’s continued use of the Product Software after such modifications are made to the Agreement will mean that Authorized Party accepts and agrees to be bound by and comply with such changes and updates.  
For Authorized Parties in California.  In compliance with California Civil Code § 1789.3, an Authorized Party residing in California has the right to contact Eaton with any complaints or to seek additional information. Such Authorized Party may email Eaton at dataprotection@eaton.com or write to: Attn: Global Data Protection and Privacy Office, Eaton, 1000 Eaton Blvd., Cleveland, OH 44122. 
If Authorized Parties in California have any questions or complaints about Eaton they may also contact: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs through writing at 400 R Street, Suite 1080, Sacramento, CA 95814, or by telephone at (916) 445-1254 or (800) 952-5210. Hearing impaired persons may call (916) 928-1227 or (800) 326-2297 via TTY device. 
Registration. To use the Product Software, Authorized Party must have a valid account with a username and password (“Credentials”). Authorized Party is responsible for maintaining the confidentiality of Authorized Party’s username and passwords, and for ensuring that each password is only used by employees granted access to the Product Software on the Authorized Party’s behalf. Authorized Party is liable for all transactions and other activities carried out under the Authorized Party’s Credentials. Authorized Party agrees to promptly notify Eaton if any password is lost, stolen, disclosed to an unauthorized party, or otherwise may have been compromised. Authorized Party agrees to immediately notify Eaton at EatonCare (877) 386-2273 of any unauthorized use of the Authorized Party’s account or any other breach of security in relation to the Product Software known to the Authorized Party. Eaton shall have no liability for any loss or damage arising from the Authorized Party’s failure to comply with these requirements. If Eaton suspends or terminates the Authorized Party’s account under this Agreement, the Authorized Party acknowledges that all information and content associated with such account will no longer be available to the Authorized Party.
Privacy Policy. Authorized Party’s registration, access and use of the Product Software is governed by the Privacy Policy located at https://www.eaton.com/content/eaton/us/en-us/company/policies-and-statements/privacy-cookies-and-data-protection.html. The Data Protection and Privacy Notice is hereby fully incorporated by this reference into this Agreement.
Confidential Information. All information provided in Product Software is Eaton’s confidential information. The Authorized Party agrees that it shall not use or disclose Eaton’s confidential information without the prior written consent of Eaton, except to share it with the Authorized Party’s employees who have a need to know the information and are bound by a duty of confidentiality covering the information that is at least as restrictive as the obligations in this Agreement. 
Except for personally identifiable information, the use and disclosure of which is addressed in the Privacy Policy for the Product Software, any and all information and content provided by the Authorized Party to Eaton is provided on a non-proprietary and non-confidential basis, regardless of whether the information or content is marked or otherwise identified as confidential or proprietary. The Authorized Party agrees that Eaton has a royalty-free, perpetual, irrevocable, worldwide, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, and display any provided information or content for the purpose of operating and/or marketing the Services or any related services rendered by Eaton. This license includes any right of publicity rights that may be present in the provided information or content.
Intellectual Property. Other than the exceptions referenced in this Agreement and noted elsewhere, all content provided through the Product Software is the sole and exclusive  property of Eaton including, but not limited to, all trade names, service marks, trademarks, logos, text, data, documents, messages, pictures, images, video, audio, graphics, links, software and its underlying code, domain names, or other electronic files (referred to hereafter as “Eaton Content”).
Certain elements of the Product Software including, but not limited to, text, graphics, photos, images, video, audio, color selections, organization and layout, are copyright protected under United States and international copyright laws. Any Eaton Content protected by intellectual property laws may not be copied, republished, posted, modified, edited, transmitted, distributed, used to create derivative works of, or reverse engineered without Eaton’s written permission.  No information, data, documents, or records found through the Product Software shall be made available as part of a website, app or online location, whether by hyperlink, framing on the internet or otherwise, without the express written consent of Eaton. 
The Authorized Party acknowledges that the Authorized Party has no right, title or interest in or to the Product Software and/or any Eaton Content. EATON and Eaton Brightlayer Industrial are trade names and/or marks owned exclusively by Eaton. The Authorized Party shall not use any trade names or marks that are confusingly similar in Eaton’s sole opinion without the prior written consent of Eaton, which may be withheld in its sole discretion. Nothing in this Agreement and nothing found through the Product Software shall be construed as a license to use any of Eaton’s trademarks, patents, copyrights, or other intellectual property rights.
There may be other content located in the Product Software that is not owned by Eaton, and the Authorized Party should respect those property rights as well. All rights not expressly granted herein are reserved to Eaton.
Termination or Suspension.  This Agreement is effective for an unlimited duration unless and until terminated as set forth herein. All rights under the license granted shall terminate automatically without notice from Eaton for failure to comply with any terms or conditions of this Agreement. Upon termination of this Agreement, the Authorized Party shall cease all use of the Product Software, and destroy all copies, full or partial, thereof. Any provision of this Agreement which by its nature must survive the termination of this Agreement in order to give effect to its meaning shall survive such termination.
Miscellaneous.  If any provision hereof becomes or is declared by a court of competent jurisdiction to be illegal, unenforceable, or void, this Agreement will continue in full force and effect without said provision. The section titles in this Agreement are for convenience only and have no legal or contractual effect. No failure or delay by Eaton or its affiliates to exercise any right or enforce any obligation shall impair or be construed as a waiver or ongoing waiver of that or any other right or power. Waiving one breach will not be construed to waive any succeeding breach. All waivers must be in writing and signed by the party waiving rights. No provisions in Authorized Party’s purchase orders, or in any other business forms employed by Authorized Party, will supersede the terms and conditions of this Agreement.
Export Rules and U.S. Government Restricted Rights.  The Authorized Party agrees not to  provide access to or use of the Product Software to any citizen of a country to which access or use thereof is barred, or to which exports or shipments are barred, or to anyone on the U.S. Treasury Department’s list of Specially Designated National or the U.S. Department of Commerce Denied Person’s List or Entity List or any other restricted parties lists by the United States government. Further, the Authorized Party will not shop, transfer or export the Product Software into any country or use the Product Software in any manner prohibited by the United States Export Administration Act or any other export laws, restrictions or regulations (collectively the "Export Laws"). In addition, if the Product Software is identified as export controlled items under the Export Laws, the Authorized Party represents and warrants that it is  not a citizen of, or otherwise located within, an embargoed nation and that it is  not otherwise prohibited under the Export Laws from receiving access to or using the Product Software. All rights to access and use of the Product Software are granted on condition that such rights are forfeited if the Authorized Party fails to comply with the terms of this Agreement.

If the Software is licensed to agencies of the U.S. Government, the Software is a "commercial item" as that term is defined at 48 C.F.R. § 2.101, consisting of "commercial computer software" and "commercial computer software documentation", as such terms are used in 48 C.F.R. § 12.212, and is provided to the U.S. Government only as a commercial end item. Consistent with 48 C.F.R. § 12.212 and 48 C.F.R. §§ 227.7202-1 through 227.7202-4, all U.S. Government End Users acquire the Software with only those rights set forth herein. Contractor/manufacturer is Eaton Corporation, 1000 Eaton Boulevard, Cleveland, Ohio 44122.

Compliance with License and Laws.  The Authorized Party agrees to comply with all federal, state, local and foreign laws, regulations, rules and ordinances pertaining to the license granted under this Agreement. In the event that any part of this Agreement is determined to violate any applicable federal, state, local or foreign laws, rules or regulations, then the remaining provisions of this Agreement shall remain in full force and effect and shall be enforced to fullest extent permitted by law.  
Governing Law and Interpretation. To the extent not prohibited by law, the Authorized Party agrees that this Agreement and all disputes, claims, actions, suits or other proceedings arising hereunder shall be governed by, and construed in accordance with, the substantive law of the State of Ohio applicable to contracts wholly made and to be performed within the State of Ohio, and to irrevocably submit to the sole and exclusive jurisdiction of the courts of Ohio or the Federal courts of the Northern District of Ohio, and to irrevocably consent to the exercise of personal jurisdiction by such courts and waive any right to plead, claim or allege that Ohio is an inconvenient forum. 
Agreement.  This Agreement constitutes the entire agreement regarding the use of the Product Software and supersedes any prior or contemporaneous understandings and agreements related to its subject matter.

Any questions regarding this Agreement should be directed to Eaton at:

Eaton 
Attn: IP Law Group
1000 Eaton Boulevard
Mail Code 4N
Cleveland, OH 44122
Email: CyberLawTeam@Eaton.com

Eaton
Attn: Global Data Protection and Privacy Office
1000 Eaton Boulevard
Cleveland, OH 44122
Email: dataprotection@eaton.com

Effective Date: November 4, 2020


PRIVACY STATEMENT/YOUR PRIVACY RIGHTS – Eaton Brightlayer Industrial

If you are in the European Economic Area (“EEA”), please click here for more information about your specific privacy rights.

Eaton Corporation (“Eaton,” “us,” “we,” or “our”) owns and operates the Eaton Brightlayer Industrial website (“Site”) and the Eaton Brightlayer Industrial Service, including mobile applications, products and services related to the Eaton Brightlayer Industrial Service (collectively, the “Services”). Eaton, as the data controller, is committed to protecting the privacy of those who visit the Site and use the Services. This Privacy Statement (“Statement”) contains details about how Eaton collects, uses, and shares with third parties Personal Data (defined below) that we obtain from and about you when interacting with Eaton and the Services. Please read this Statement carefully. If you not agree with our policies and practices, do not download, install or operate the Services, do not access or use the Site, and do not interact with any other part of the Services.  

Applicability: This Statement covers only the Services identified above and does not apply to information that you may send us by other means or related to other Eaton products or services. Other Eaton sites, applications and online services or locations may have their own privacy statements, and you should consult those accordingly. This Statement also does not apply to job applicants or Eaton employees.

Whenever you interact with Eaton or the Services on behalf of another individual or entity, such as by providing or accessing Personal Data about another individual, you represent that you have the authority to do so. You shall have sole responsibility for any violation of privacy laws as a result of a failure to obtain any necessary consent from such individual/entity.

Changes: Eaton may update this Statement from time to time. The current Statement will be posted on the Site and available via a link provided to you and will be effective when posted. Please check this Statement periodically for updates. If any of the changes are unacceptable to you, you should cease using the Services. When required, we will notify you of any changes to this Statement. If any changes to this Statement materially affect how Eaton treats or handles Personal Data that you have already provided to Eaton or that has otherwise been collected by us, or when required under applicable laws, we will seek affirmative consent from you, by email (if we have a valid email address to use), to use it in the new manner. If you do not provide such consent, Personal Data will continue to be used in a manner that is consistent with the version of this Statement under which it was collected, or the information will be deleted. 

What Information Do We Collect? 
Personal Data (“Personal Data”) is any information relating to an identified or identifiable natural person (“Data Subject”).  

Sources of Personal Data:
We collect information about you and how you use the Services in several ways, including:

Information you provide to us directly. We collect the information you provide to us directly, such as when registering on the Site, signing up for offers, or communicating with us. 
Information collected or inferred from your use of the Services. We collect information about the Services and how you use them, such as information collected automatically when you visit or use our Site, download a mobile application, or otherwise interact with the Services.
Information from third parties. We receive information about you and your use of the Services from third parties, such as from your employer or coworkers, third party service and content providers, companies that provide or sell lists of potential purchasers, and other Services users. 

We may combine information that we receive from the various sources described in this Privacy Statement, including third party sources, with Personal Data and use or disclose it for the purposes identified below.

Information We Collect:
The types of information that Eaton collects about you include:

Contact and account information, such as your name, work postal address, work email address, work phone number, user name, work email address, employee identification number, and work company name
Technical information gathered when you interact with the Services, such as IP address, browser information, ICCID, device type, app and OS version
Internet or other electronic network activity information, such as your browsing history, search history, and information regarding your interactions with and use of the Services (including the Site, mobile application, and advertisements) 
Employment information, such as job title, employment history, or other professional information

How Do We Use Your Personal Data?
We may use your information in a number of ways, including:

To provide you with the Services, such as to register and administer your account, provide Services you may request; support your Services; diagnose, repair and track service and quality issues; communicate with you about your Services; install and configure changes and updates to your Services; authenticate users of our Services; verify your eligibility for certain programs or benefits; or to respond to your requests, complaints, and inquiries.
For our own internal business purposes, such as to evaluate or audit the usage, performance and safety of our Services; evaluate and improve the quality of our Services and design new services; operate the Site and customize the content; internal research purposes; display or evaluate the effectiveness of our advertising or marketing efforts; or maintain internal business records.
For legal, safety or security reasons, such as to comply with legal requirements; protect the safety, property or rights of Eaton, Services users, or others; and detect, prevent, and respond to security incidents or other malicious, deceptive, fraudulent, or illegal activity.
In an anonymous or aggregated format. We may also use your information in an anonymized or aggregate manner for any purpose.

With Whom Do We Share Your Information?
We may share your Personal Data with entities other than the Eaton entity that originally collected it, including the categories of recipients described below:

Affiliates and subsidiaries: We may share your Personal Data within the Eaton group of companies, which includes parents, corporate affiliates, subsidiaries, business units and other companies that share common ownership for the purposes described above. 
Third party service providers: We may share your Personal Data with third party service providers working on behalf of Eaton in order to provide the Services you request or support our relationship with you, such as IT providers, accountants, analytics companies, and marketing providers.
For legal, security and safety purposes: We may share your Personal Data with third parties such as law enforcement or other government agencies to comply with law or legal requirements; to enforce or apply our Terms of Use and other agreements; and to protect our rights and the property or safety of Eaton, our users, or third parties. 
In connection with a transaction: If we, or some or all of our assets, are acquired by another entity, including through a sale in connection with bankruptcy, we will share your Personal Data with that entity.
Your employer or coworkers: If you receive the Services in connection with your employment, your employer, coworkers, or other individuals designated by your employer may view any Personal Data that we collect in connection with your use of or interaction with the Services.
Eaton does not sell your Personal Data or share it with third parties for their direct marketing purposes.

Cookies and Other Tracking Technologies
Please click here for information about how we use cookies and other tracking technologies, including online behavioral advertising.  

Data Security and Retention
Eaton maintains reasonable security procedures and technical and organizational measures to protect your Personal Data against accidental or unlawful destruction, loss, disclosure or use of personal data we handle. When handling your Personal Data for our business functions, Eaton will limit access to your Personal Data to authorized persons and trusted third parties who have a reasonable need to know the information in order to perform our Services who are bound by confidentiality obligations. While Eaton takes the issue of protecting your Personal Data seriously, you should exercise discretion in what information you disclose and/or transmit through the Services. Eaton cannot guarantee that information sent over the Internet is fully secure, and therefore the transmitted information may be intercepted by others before it reaches Eaton. If you are concerned about sending information to Eaton over the Internet, please send the information by mail or call us to make other arrangements. Eaton is not responsible for the security of information sent over the Internet.

Eaton retains Personal Data only for as long as necessary to fulfill the stated purpose for which the Personal Data was collected or otherwise processed, and thereafter only for legitimate legal or business purposes. These may include retention periods that are: (i) mandated by law, contract or similar obligations applicable to Eaton’s business operations; (ii) for preserving, resolving, defending or enforcing our legal/contractual rights; or (iii) needed to maintain adequate and accurate business and financial records. We will delete Personal Data as soon as the respective purpose for its use is complete and no legal obligation to retain such data exists.  

Children’s Privacy
The Services are intended for individuals 18 years of age and older. The Services are not directed at, marketed to, nor intended for, children under 18 years of age. Eaton does not knowingly collect any information, including Personal Data, from children under 18 years of age. If you believe that we have inadvertently collected Personal Data from a child under the age of 18, please contact us at the address below and we will take immediate steps to delete the information.    

External Links 
The Services may contain links to external sites or other online services, including those embedded in third party advertisements or sponsor information, that are not controlled by Eaton. Eaton is not responsible for the privacy practices and data collection policies for such third party services. You should consult the privacy statements of those third party services for details.  

Terms of Use 
The End-User License Agreement for the Services is incorporated by reference into this Statement, and can be found at:__ https://brightlayer-ind.eaton.com/legal/eula.

Contact Info/Your Choices 
If you have questions regarding this Statement, please contact Eaton at:

Eaton
Attention: Global Data Protection and Privacy Office
1000 Eaton Boulevard
Cleveland, Ohio 44122
dataprotection@eaton.com

To opt-out of receiving promotional email messages from us, please click on the "Unsubscribe" link contained at the bottom of each email or by contacting us using the information above.
EEA Section
This section applies if you are an EEA data subject. In the event of a conflict between information in this section and the rest of the Statement, this EEA Section will govern.  

Our legal basis for collecting and using the Personal Data as data controllers will depend on the Personal Data concerned and the specific context in which we collect it. In many cases, we will process Personal Data about you using the following legal basis:
Legitimate interest – we process Personal Data to meet our legitimate business interests, such as to develop and improve our solutions, support our sales and business operations, and secure our systems, facilities and personnel.
Legal obligation – we process Personal Data to comply with applicable laws and regulations.  
Performance of Agreement – we process Personal Data in order to perform or fulfill our obligations under an agreement with you or the entity with which you are affiliated.  
Consent – We may process your Personal Data based on consent. For example, if we want to send you a marketing communication, we will seek your consent separately at the time of collection. You may withdraw your consent at any time by contacting us at the information in the “Contact Us” Section above.

International Transfers of Your Personal Data
By using the Site or providing Personal Data to Eaton, your Personal Data is transferred to the United States where Eaton is headquartered. If you are not a resident of the United States, your country’s laws governing data collection and use may differ from those in the United States. For example, the data protection laws of the United States have not been found by the European Commission to provide the same level of protection as EU data protection law. Transfers to countries outside the European Economic Area (“EEA”) take place using an acceptable data transfer mechanism, such as the EU-U.S. Privacy Shield, the EU Standard Contractual Clauses, Binding Corporate Rules, approved Codes of Conduct and Certifications, or on the basis of permissible statutory derogations. Please contact dataprotection@eaton.com, if you want to receive further information or, where available, a copy of the relevant data transfer mechanism.

EU-U.S. Privacy Shield
Your Personal Data may be transferred to and processed in countries other than the country in which you are a resident. These countries may have data protection and privacy laws that are different to the laws of your country. You can find out more about the relevant countries by visiting https://www.eaton.com/us/en-us/company/policies-and-statements/privacy-cookies-and-data-protection/international-data-transfers--privacy-shield-information.html or contacting us (see below).

To learn more about the Privacy Shield program, the Privacy Shield Principles and to view our certification page, please visit the U.S. Department of Commerce’s Privacy Shield List by clicking on the following link: http://www.commerce.gov/privacyshield/

Your EEA Privacy Rights
If you are visiting the Site from the EEA or where EEA data protection laws apply, with certain legal exceptions and limitations, you may exercise the following rights regarding your Personal Data:

Access. You have the right to confirm with us if your Personal Data is being processed and certain other information about that processing.

Rectification. You have the right to request the rectification of inaccurate Personal Data and to have incomplete data completed.

Objection. You have the right to object to the processing of your Personal Data for compelling and legitimate reasons. In addition, you have the right to object at any time if your Personal Data is processed for direct marketing purposes.

Portability. You may receive Personal Data that you have provided to us in a structured, commonly used and machine-readable format and have the right to transmit that data to others. 

Restriction. You may request to restrict processing of your Personal Data.

Erasure. You may request to erase your Personal Data.

Right to lodge a complaint. You also have the right to lodge a complaint with a supervisory authority, in particular in the EU Member State of your residence.

Right to refuse or withdraw consent. Please note that in case we ask for your consent to certain processing, you are free to refuse to give consent and you can withdraw your consent at any time without any adverse negative consequences. The lawfulness of any processing of your Personal Data that occurred prior to the withdrawal of your consent will not be affected.

Right not to be subject to automatic decision-making, including profiling.

If you have questions about exercising any of your rights or whether they apply to a particular processing activity, you may contact us at: dataprotection@eaton.com.
How We Use Cookies and Automatic Data Collection Tools
When you visit an Eaton Site, open an e-mail marketing communication or download an Eaton mobile application, we or our third party service provider may collect information through the use of a "cookie" or other device recognition technology. These tools send a small file to your browser that is unique to you and can only be read by our or our third party service providers’ web servers. These files provide information that helps us customize your experience on our websites and provide relevant advertising to you.
Types of Cookies We Use
We or our third party service providers may use cookies to collect information about your and other visitor’s browsing behavior such as IP address, type of browser used, domain name and pages visited. This information is used to learn about the usage and effectiveness of our web properties in order to improve how our website works and for advertising purposes. These cookies are session and persistent cookies.  Some cookies may be used to track you across devices.
Specifically, we use the following cookies and tools:
Purpose	Provider/Type
Capture web metrics such as how often users visit the Site, what pages they visit when they do so, how long they leave the dashboard open, how often they acknowledge an alarm, what time of day they access the Site, and what site referred a user to this Site.	Microsoft Azure, see Microsoft Privacy Statement

Changing Cookie Preferences
Most browsers are set to accept cookies. Using the “help” feature on your browser (e.g., Google; Microsoft; Apple; Mozilla), you can manage your browser cookie preferences to, for example, automatically accept cookies, automatically decline cookies, or notify you before receiving a cookie.
You can find more information about cookies generally at: www.allaboutcookies.org.
If you use our websites and choose not to disable cookies, you agree that we or our service provider can place them on your device. Please note that refusing a cookie may affect your ability to access certain content or functionality offered by our website. We do not process or honor other “Do Not Track” signals.
Online Advertising
Eaton advertises on the websites of third parties. These third parties may use cookies or tools to gather information about your browsing activities in order to provide advertising relevant to your interests.
You can manage your receipt of targeted advertising by visiting these websites: in the EU, https://www.youronlinechoices.eu/ and for U.S. and other regions, http://www.aboutads.info/consumers.
Marketing Communications
We provide digital marketing communications about our Services with an unsubscribe mechanism in each communication. You can unsubscribe from any particular communication by clicking on “unsubscribe” in the email itself.

This Statement was last updated on November 4, 2020.`;
